// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/lecterkn/goat_backend/internal/app/database"
	"github.com/lecterkn/goat_backend/internal/app/handler"
	"github.com/lecterkn/goat_backend/internal/app/provider"
	"github.com/lecterkn/goat_backend/internal/app/repository/mysql"
	"github.com/lecterkn/goat_backend/internal/app/repository/redis"
	"github.com/lecterkn/goat_backend/internal/app/usecase"
)

// Injectors from wire.go:

func InitializeHandlerSet() *HandlerSet {
	db := database.GetMySQLConnection()
	userRepository := mysql.NewUserRepositoryImpl(db)
	client := database.GetRedisClient()
	tokenRepository := redis.NewTokenRepositoryImpl(client)
	authorizationUsecase := usecase.NewAuthorizationUsecase(userRepository, tokenRepository)
	authorizationHandler := handler.NewAuthorizationHandler(authorizationUsecase)
	categoryRepository := mysql.NewCategoryRepositoryImpl(db)
	categoryUsecase := usecase.NewCategoryUsecase(userRepository, categoryRepository)
	categoryHandler := handler.NewCategoryHandler(categoryUsecase)
	storyRepository := mysql.NewStoryRepositoryImpl(db)
	storyUsecase := usecase.NewStoryUsecase(userRepository, storyRepository, categoryRepository)
	storyHandler := handler.NewStoryHandler(storyUsecase)
	transactionProvider := provider.NewTransactionProviderImpl(db)
	userUsecase := usecase.NewUserUsecase(userRepository, transactionProvider)
	userHandler := handler.NewUserHandler(userUsecase)
	myListRepository := mysql.NewMyListRepositoryImpl(db)
	myListUsecase := usecase.NewMyListUsecase(storyRepository, myListRepository, transactionProvider)
	myListHandler := handler.NewMyListHandler(myListUsecase)
	diHandlerSet := &HandlerSet{
		AuthorizationHandler: authorizationHandler,
		CategoryHandler:      categoryHandler,
		StoryHandler:         storyHandler,
		UserHandler:          userHandler,
		MyListHandler:        myListHandler,
	}
	return diHandlerSet
}

// wire.go:

var databaseSet = wire.NewSet(database.GetMySQLConnection, database.GetRedisClient)

var repositorySet = wire.NewSet(mysql.NewUserRepositoryImpl, mysql.NewCategoryRepositoryImpl, mysql.NewStoryRepositoryImpl, redis.NewTokenRepositoryImpl, mysql.NewMyListRepositoryImpl)

var providerSet = wire.NewSet(provider.NewTransactionProviderImpl)

var usecaseSet = wire.NewSet(usecase.NewAuthorizationUsecase, usecase.NewCategoryUsecase, usecase.NewStoryUsecase, usecase.NewUserUsecase, usecase.NewMyListUsecase)

var handlerSet = wire.NewSet(handler.NewAuthorizationHandler, handler.NewCategoryHandler, handler.NewStoryHandler, handler.NewUserHandler, handler.NewMyListHandler)

type HandlerSet struct {
	AuthorizationHandler *handler.AuthorizationHandler
	CategoryHandler      *handler.CategoryHandler
	StoryHandler         *handler.StoryHandler
	UserHandler          *handler.UserHandler
	MyListHandler        *handler.MyListHandler
}
