basePath: /api
definitions:
  request.UserSigninRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  request.UserSignupRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  response.UserSigninResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    required:
    - accessToken
    - refreshToken
    type: object
  response.UserSignupResponse:
    properties:
      createdAt:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      updatedAt:
        type: string
    required:
    - createdAt
    - email
    - id
    - name
    - updatedAt
    type: object
host: localhost:8993
info:
  contact: {}
  description: MyAnimeGameList API Server
  title: MyAnimeGameList
  version: "1.0"
paths:
  /signin:
    post:
      description: ユーザーのサインインを行う
      parameters:
      - description: ユーザーログインリクエスト
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserSigninRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserSigninResponse'
      summary: SignIn
      tags:
      - user
  /signup:
    post:
      description: ユーザーのサインアップを行う
      parameters:
      - description: ユーザーログインリクエスト
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.UserSignupRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserSignupResponse'
      summary: SignUp
      tags:
      - user
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
